# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, actions ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: remote deploy
      uses: appleboy/ssh-action@v0.0.2
      env:
        REMOTE_PID_FILE: "/tmp/2020-pid"
        REMOTE_REPO_DIR: "~"
        REPO_NAME: "20-20"
      with:
        host: "104.40.27.221"
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: "22"
        script: |
          whoami
